theme: jekyll-theme-minimal
title: James Motes
description: Computer Science and Robotics Faculty Candidate

# Navigation
header_pages:
  - index.md
  - research.md
  - publications.md
  - teaching.md
  - news.md
  - about.md
